DROP TABLE IF EXISTS SUBMISSION_EDITOR_CHASERS;
DROP TABLE IF EXISTS SUBMISSION_EDITOR_INVITATIONS;
DROP TABLE IF EXISTS SUBMISSION_REVIEWERS;
DROP TABLE IF EXISTS SUBMISSIONS;
DROP TABLE IF EXISTS SUBMISSION_HISTORY;

CREATE TABLE SUBMISSIONS
(
    SUBMISSION_ID UUID PRIMARY KEY NOT NULL,
    TITLE         VARCHAR(200)     NOT NULL,
    ABSTRACT      TEXT             NOT NULL,
    EDITOR_ID     UUID,
    VERSION       INT              NOT NULL
);

CREATE TABLE SUBMISSION_REVIEWERS
(
    SUBMISSION_ID UUID REFERENCES SUBMISSIONS (SUBMISSION_ID),
    REVIEWER_ID   UUID NOT NULL,
    PRIMARY KEY (SUBMISSION_ID, REVIEWER_ID)
);

CREATE TABLE SUBMISSION_EDITOR_INVITATIONS
(
    SUBMISSION_ID UUID REFERENCES SUBMISSIONS (SUBMISSION_ID),
    EDITOR_ID     UUID        NOT NULL,
    STATE         VARCHAR(30) NOT NULL,
    PRIMARY KEY (SUBMISSION_ID, EDITOR_ID)
);

CREATE TABLE SUBMISSION_EDITOR_CHASERS
(
    SUBMISSION_ID UUID REFERENCES SUBMISSIONS (SUBMISSION_ID),
    EDITOR_ID     UUID        NOT NULL,
    CHASE_TIME    TIMESTAMP   NOT NULL,
    STATE         VARCHAR(30) NOT NULL,
    PRIMARY KEY (SUBMISSION_ID, EDITOR_ID)
);

CREATE TABLE SUBMISSION_HISTORY
(
    SUBMISSION_ID UUID         NOT NULL,
    EVENT_NUMBER  INT          NOT NULL,
    EVENT_TIME    TIMESTAMP    NOT NULL,
    EVENT_TYPE    VARCHAR(100) NOT NULL,
    DESCRIPTION   VARCHAR(2000),
    PRIMARY KEY (SUBMISSION_ID, EVENT_NUMBER)
);

